webtalk_init -webtalk_dir F:/Documents/Uni/CSSE4010/prac4/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/test_output_hold_mealy_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 23 20:29:45 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d5b6667f-a33d-4f94-9ad9-469786cb2ca0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2316248bb24b4094b8f28b9c03343002" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8350 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3886 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6008_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1725946585 -regid "" -xml F:/Documents/Uni/CSSE4010/prac4/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/test_output_hold_mealy_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Documents/Uni/CSSE4010/prac4/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/test_output_hold_mealy_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Documents/Uni/CSSE4010/prac4/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/test_output_hold_mealy_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
